ansible_host: 192.133.177.18
ansible_port: 20000
interfaces:
  GigabitEthernet2:
    enabled: true
    nat: outside
    ip:
      primary: 192.133.177.27/25
      gateway: 192.133.177.1
  GigabitEthernet3:
    enabled: true
    nat: inside
    ip:
      primary: 192.168.0.1/24

nat:
  - type: inside
    source: list
    list: nat
    interface: GigabitEthernet2
    overload: true

access_lists:
  - name: nat
    type: standard
    rules:
      - action: permit
        source: 192.168.0.0/16
        
router:
  ospf:
    id: 1
    router_id: 192.168.0.1
    networks:
      - network: 192.168.0.0/24
        area: 0