ansible_python_interpreter: /usr/bin/python3
ansible_host: "{{ hostvars['harness'].ansible_host }}"
ansible_port: 20012
ansible_user: fedora
interfaces:
  eth1:
    enabled: true
    ip:
      primary: 192.168.0.10/24
    routes:
      - network: 192.168.0.0/16
        gateway: 192.168.0.2