- hosts: localhost
  gather_facts: no
  vars:
    image_dir: ./images
    tmp_dir: /tmp
    old_iso: Cisco_NFVIS_BRANCH-3.12.2-FC2.iso
    new_iso: nfvis_3phw.iso
    nfvis_3phw: nfvis_3phw.json
    old_iso_dir: "{{ tmp_dir }}/oldiso"
    new_iso_dir: "{{ tmp_dir }}/newiso"
  tasks:
    - name: Create mount point {{ old_iso_dir }}
      file:
        path: "{{ old_iso_dir }}"
        state: directory

    - name: Mount {{ image_dir }}/{{ old_iso }} to {{ old_iso_dir }}
      command: "/usr/bin/fuseiso {{ image_dir }}/{{ old_iso }} {{ old_iso_dir }}"

    - name: Get ISO label
      shell: "/sbin/blkid {{ image_dir }}/{{ old_iso }} | awk '{print $3}' | awk -F\\\" '{print $2}'"
      register: volume_id_raw

    - name: assign volume_id variable
      set_fact:
        volume_id: "{{ volume_id_raw.stdout }}"

    - name: Copy {{ old_iso_dir }} to {{ new_iso_dir }}
      copy:
        src: "{{ old_iso_dir }}/"
        dest: "{{ new_iso_dir }}/"

    - name: Copy {{ nfvis_3phw }} to {{ new_iso_dir }}
      copy:
        src: nfvis_3phw.json
        dest: "{{ new_iso_dir }}"

    - name: get current directory
      shell: "pwd"
      register: pwd

    - name: Create {{ image_dir }}/{{ new_iso }} from {{ new_iso_dir }}
      command:
        chdir: "{{ new_iso_dir }}"
        cmd: "/usr/bin/mkisofs -V {{ volume_id }} -J -R -T -v -f -no-emul-boot -boot-load-size 4 -boot-info-table -b isolinux/isolinux.bin -c isolinux/boot.cat -x \"lost+found\" --joliet-long -eltorito-alt-boot -e images/efiboot.img -no-emul-boot  -r -o {{ pwd.stdout }}/{{ image_dir }}/{{ new_iso }} ."
