---
- name: Wait for VNFs to boot (timeout 10min)
  hosts: control_host:test_host
  gather_facts: no
  tags:
    - wait
  tasks:
    - wait_for:
        port: 22
        host: "{{ ansible_host }}"
        timeout: 600
      delegate_to: localhost

- name: Prep the control host
  hosts: control_host:test_host
  gather_facts: no
  become: yes
  tags:
    - control
  vars:
    package_list:
      - iperf3_3.1.3-1_amd64.deb
      # - libiperf0_3.1.3-1_amd64.deb
  tasks:
    - name: Copy .deb packages
      copy:
        src: "{{ item }}"
        dest: /tmp
      loop: "{{ package_list }}"

    - name: Disable apt auto updates
      systemd:
        name: "{{ item }}"
        state: stopped
        enabled: no
      loop:
        - apt-daily.timer
        - apt-daily-upgrade.timer

    - name: Install .deb packages
      command: apt install "/tmp/{{ item }}"
      loop: "{{ package_list }}"
      register: dpkg

- name: Prep the test hosts
  hosts: control_host
  gather_facts: no
  become: yes
  tags:
    - test
  tasks:
    - name: Copy iperf systemd
      copy:
        src: iperf3.service
        dest: /etc/systemd/system

    - name: Make sure a service is running
      systemd:
        name: iperf3
        state: started
        enabled: yes
