---
- name: Wait for VNFs to boot (timeout 10min)
  hosts: test_host
  gather_facts: no
  tags:
    - wait
  tasks:
    - wait_for:
        port: "{{ ansible_port | default('22') }}"
        host: "{{ ansible_host }}"
        timeout: 600
      delegate_to: localhost

- name: Prep the test hosts
  hosts: test_host
  gather_facts: no
  become: yes
  tags:
    - control
  vars:
    package_list:
      - libuuid-devel-2.32.1-1.fc28.x86_64.rpm
      - iperf3-3.5-1.fc28.src.rpm

  tasks:
    - name: Copy packages
      copy:
        src: "{{ item }}"
        dest: /tmp
      loop: "{{ package_list }}"

    # - name: Disable apt auto updates
    #   systemd:
    #     name: "{{ item }}"
    #     state: stopped
    #     enabled: no
    #   loop:
    #     - apt-daily.timer
    #     - apt-daily-upgrade.timer

    # - name: Install .deb packages
    #   command: dpkg -i  "/tmp/{{ item }}"
    #   loop: "{{ package_list }}"
    #   register: dpkg

    # - name: Disable repositories
    #   yum_repository:
    #     name: '*'
    #     state: absent

    - name: Install packages
      yum:
        name: "/tmp/{{ item }}"
        update_cache: no
        state: installed
        disablerepo: "*"
      loop: "{{ package_list }}"

- name: Prep the test hosts
  hosts: test_host
  gather_facts: no
  become: yes
  tags:
    - test
  tasks:
    # - name: Copy iperf systemd
    #   copy:
    #     src: iperf3.service
    #     dest: /etc/systemd/system

    - name: Make sure a service is running
      systemd:
        name: iperf3
        state: started
        enabled: yes
