nfvis:
  name: "{{ inventory_hostname }}"
  host: "{{ hostvars['harness'].ansible_host }}"
  image: fedora
  flavor: fedora-small
  bootup_time: -1
  interfaces:
    - network: wan-net
    - network: test-wan
  config_data:
    - dst: meta-data
      data: "{{ lookup('template', 'fedora/meta-data.j2') }}"
    - dst: user-data
      data: "{{ lookup('template', 'fedora/user-data.j2') }}"
    - dst: network-config
      data: "{{ lookup('template', 'fedora/network-config_no-mgmt.j2') }}"