ansible_host: 127.0.01
netmask: 24
pxe_mac: "00:aa:bb:cc:dd:ee"
pxe_ip: "{{ test_lan_cidr | ipaddr('net') | ipaddr('5') | ipaddr('address') }}"
nfvis_bridges:
  service:
nfvis_networks:
  test-wan:
    bridge: wan-br
    trunk: no
    vlan: "{{ test_wan_vlan }}"
  test-lan:
    bridge: lan-br
    trunk: no
    vlan: "{{ test_lan_vlan }}"
  service:
    bridge: service
interfaces:
  mgmt:
    ip:
      primary: "{{ ansible_host }}/{{ netmask }}"
      gateway: "{{ ansible_host }}/{{ netmask }} | ipaddr('net') | ipaddr('1') }}"

# this is the port we specify as the pxe_mac
test_wan_switchport: gi1/2
test_wan_localport: eth0

test_lan_switchport: gi1/3
test_lan_localport: eth1
