ansible_host: 192.133.177.18
nfvis_networks:
  test-wan:
    bridge: lan-br
    trunk: no
    vlan: 4000
  test-lan:
    bridge: lan-br
    trunk: no
    vlan: 4001  
interfaces:
  mgmt:
    ip:
      primary: 192.133.177.18/25
      gateway: 192.133.177.1